; Note: This file contains all the defines that aren't for the different kinds of RAM.

!Define_SMW_MaxNormalSpriteSlot = $0B
!Define_SMW_MaxBounceSpriteSlot = $03
!Define_SMW_MaxScoreSpriteSlot = $05
!Define_SMW_MaxSpinningCoinSpriteSlot = $03
!Define_SMW_MaxMinorExtendedSpriteSlot = $0B
!Define_SMW_MaxExtendedSpriteSlot = $09
!Define_SMW_MaxClusterSpriteSlot = $13
!Define_SMW_MaxShooterSpriteSlot = $07
!Define_SMW_MaxSmokeSpriteSlot = !Define_SMW_MaxBounceSpriteSlot
!Define_SMW_MaxCutsceneSpriteSlot = $0E
!Define_SMW_MaxOverworldSpriteSlot = $0F
!Define_SMW_MaxSwitchBlockSlot = $27
!NullSpriteSlot = $FF

;struct SprSlot $00
;	.NorSpr
;	.ExtSpr
;	.MExtSpr
;	.BounceSpr
;	.ScoreSpr
;	.SpinningCoinSpr
;	.ClusterSpr
;	.ShooterSpr
;	.SmokeSpr
;	.CutsceneSpr
;	.OWSpr
;	.SwitchBlockSpr skip $01
;endstruct

!Define_SMW_Sound1DF9_HitHead = $01
!Define_SMW_Sound1DF9_Contact = $02
!Define_SMW_Sound1DF9_KickShell = $03
!Define_SMW_Sound1DF9_IntoPipe = $04
!Define_SMW_Sound1DF9_MidwayPoint = $05
!Define_SMW_Sound1DF9_YoshiGulp = $06
!Define_SMW_Sound1DF9_DryBonesCollapse = $07
!Define_SMW_Sound1DF9_SpinJumpKill = $08
!Define_SMW_Sound1DF9_FlyWithCape = $09
!Define_SMW_Sound1DF9_GetPowerup = $0A
!Define_SMW_Sound1DF9_ONOFFSwitch = $0B
!Define_SMW_Sound1DF9_CarryItemToGoal = $0C
!Define_SMW_Sound1DF9_GetCape = $0D
!Define_SMW_Sound1DF9_Swim = $0E
!Define_SMW_Sound1DF9_HurtWhileFlying = $0F
!Define_SMW_Sound1DF9_MagicShoot = $10
!Define_SMW_Sound1DF9_Pause = $11
!Define_SMW_Sound1DF9_UnPause = $12
!Define_SMW_Sound1DF9_Stomp1 = $13
!Define_SMW_Sound1DF9_Stomp2 = $14
!Define_SMW_Sound1DF9_Stomp3 = $15
!Define_SMW_Sound1DF9_Stomp4 = $16
!Define_SMW_Sound1DF9_Stomp5 = $17
!Define_SMW_Sound1DF9_Stomp6 = $18
!Define_SMW_Sound1DF9_Stomp7 = $19
!Define_SMW_Sound1DF9_Grinder1 = $1A
!Define_SMW_Sound1DF9_Grinder2 = $1B
!Define_SMW_Sound1DF9_YoshiCoin = $1C
!Define_SMW_Sound1DF9_RunningOutOfTime = $1D
!Define_SMW_Sound1DF9_PBalloon = $1E
!Define_SMW_Sound1DF9_KoopalingDead = $1F
!Define_SMW_Sound1DF9_YoshiSpit = $20
!Define_SMW_Sound1DF9_ValleyOfBowserAppears = $21
!Define_SMW_Sound1DF9_EndValleyOfBowserAppears = $22				; Note: This is not listed on SMWCentral's sound list page (https://www.smwcentral.net/?p=viewthread&t=6665)
!Define_SMW_Sound1DF9_LemmyWendyFall = $23
!Define_SMW_Sound1DF9_Unused = $24						; Note: This one is also not listed
!Define_SMW_Sound1DF9_BlarggRoar = $25
!Define_SMW_Sound1DF9_FireworksWhistle = $26
!Define_SMW_Sound1DF9_FireworksBang = $27
!Define_SMW_Sound1DF9_LouderFireworksWhistle = $28
!Define_SMW_Sound1DF9_LouderFireworksBang = $29
!Define_SMW_Sound1DF9_PeachPoppingOutOfClownCar = $2A
!Define_SMW_Sound1DF9_IncreaseMusicTempo = $FF

!Define_SMW_Sound1DFA_Jump = $01
!Define_SMW_Sound1DFA_TurnOnYoshiDrum = $02
!Define_SMW_Sound1DFA_TurnOffYoshiDrum = $03
!Define_SMW_Sound1DFA_Grinder = $04

!Define_SMW_LevelMusic_Piano = $01
!Define_SMW_LevelMusic_HereWeGo = $02
!Define_SMW_LevelMusic_WaterLevel = $03
!Define_SMW_LevelMusic_FightBowser1 = $04
!Define_SMW_LevelMusic_BossBattle = $05
!Define_SMW_LevelMusic_CaveDrums = $06
!Define_SMW_LevelMusic_GhostHouse = $07
!Define_SMW_LevelMusic_Castle = $08
!Define_SMW_LevelMusic_MarioDied = $09
!Define_SMW_LevelMusic_GameOver = $0A
!Define_SMW_LevelMusic_PassedBoss = $0B
!Define_SMW_LevelMusic_PassedLevel = $0C
!Define_SMW_LevelMusic_HaveStar = $0D
!Define_SMW_LevelMusic_DirectCoins = $0E
!Define_SMW_LevelMusic_IntoKeyhole1 = $0F
!Define_SMW_LevelMusic_IntoKeyhole2 = $10
!Define_SMW_LevelMusic_ZoomIn = $11
!Define_SMW_LevelMusic_SwitchPalace = $12
!Define_SMW_LevelMusic_Welcome = $13
!Define_SMW_LevelMusic_DoneBonusGame = $14
!Define_SMW_LevelMusic_RescueEgg = $15
!Define_SMW_LevelMusic_FightBowser2 = $16
!Define_SMW_LevelMusic_BowserZoomOut = $17
!Define_SMW_LevelMusic_BowserZoomIn = $18
!Define_SMW_LevelMusic_FightBowser3 = $19
!Define_SMW_LevelMusic_FightBowser4 = $1A
!Define_SMW_LevelMusic_BowserDied = $1B
!Define_SMW_LevelMusic_PrincessKiss = $1C
!Define_SMW_LevelMusic_BowserInterlude = $1D
!Define_SMW_LevelMusic_MusicFade = $80
!Define_SMW_OverworldMusic_TitleScreen = $01
!Define_SMW_OverworldMusic_Overworld = $02
!Define_SMW_OverworldMusic_YoshisIsland = $03
!Define_SMW_OverworldMusic_VanillaDome = $04
!Define_SMW_OverworldMusic_StarRoad = $05
!Define_SMW_OverworldMusic_ForestOfIllusion = $06
!Define_SMW_OverworldMusic_BowsersValley = $07
!Define_SMW_OverworldMusic_BowsersValleyRevealed = $08
!Define_SMW_OverworldMusic_SpecialWorld = $09
!Define_SMW_CreditsMusic_StaffRoll = $09
!Define_SMW_CreditsMusic_TheYoshisAreHome = $0A
!Define_SMW_CreditsMusic_CastList = $0B

!Define_SMW_Sound1DFC_Coin = $01
!Define_SMW_Sound1DFC_HitItemBlock = $02
!Define_SMW_Sound1DFC_HitVineBlock = $03
!Define_SMW_Sound1DFC_SpinJump = $04
!Define_SMW_Sound1DFC_1up = $05
!Define_SMW_Sound1DFC_ShootFireball = $06
!Define_SMW_Sound1DFC_BreakBlock = $07
!Define_SMW_Sound1DFC_Springboard = $08
!Define_SMW_Sound1DFC_BulletShoot = $09
!Define_SMW_Sound1DFC_EggHatch = $0A
!Define_SMW_Sound1DFC_PutItemInReserve = $0B
!Define_SMW_Sound1DFC_DropItemInReserve1 = $0C
!Define_SMW_Sound1DFC_DropItemInReserve2 = $0D
!Define_SMW_Sound1DFC_LRScroll = $0E
!Define_SMW_Sound1DFC_Door1 = $0F
!Define_SMW_Sound1DFC_Door2 = $10
!Define_SMW_Sound1DFC_DrumrollStart = $11
!Define_SMW_Sound1DFC_DrumrollEnd = $12
!Define_SMW_Sound1DFC_LoseYoshi = $13
!Define_SMW_Sound1DFC_Unused = $14
!Define_SMW_Sound1DFC_OverworldTileReveal = $15
!Define_SMW_Sound1DFC_CastleCollapse = $16
!Define_SMW_Sound1DFC_FireSpit = $17
!Define_SMW_Sound1DFC_Thunder = $18
!Define_SMW_Sound1DFC_Clap = $19
!Define_SMW_Sound1DFC_Explosion = $1A
!Define_SMW_Sound1DFC_TNTFuse = $1B
!Define_SMW_Sound1DFC_OverworldSwitchBlockEjection = $1C
!Define_SMW_Sound1DFC_RunningOutOfTime = $1D
!Define_SMW_Sound1DFC_ChuckWhistle = $1E
!Define_SMW_Sound1DFC_MountYoshi = $1F
!Define_SMW_Sound1DFC_LemmyWendyLandInLava = $20
!Define_SMW_Sound1DFC_YoshiTongue = $21
!Define_SMW_Sound1DFC_MessageBox = $22
!Define_SMW_Sound1DFC_StepOnLevelTile = $23
!Define_SMW_Sound1DFC_PSwitchRunningOut = $24
!Define_SMW_Sound1DFC_YoshiStompsEnemy = $25
!Define_SMW_Sound1DFC_Swooper = $26
!Define_SMW_Sound1DFC_Podoboo = $27
!Define_SMW_Sound1DFC_StunEnemy = $28
!Define_SMW_Sound1DFC_Correct = $29
!Define_SMW_Sound1DFC_Wrong = !Define_SMW_Sound1DFC_Correct+$01
!Define_SMW_Sound1DFC_FireworksWhistle = $2B
!Define_SMW_Sound1DFC_FireworksBang = $2C
!Define_SMW_Sound1DFC_PodobooPan1 = $2D
!Define_SMW_Sound1DFC_PodobooPan2 = $2E
!Define_SMW_Sound1DFC_PodobooPan3 = $2F
!Define_SMW_Sound1DFC_PodobooPan4 = $30
!Define_SMW_Sound1DFC_PodobooPan5 = $31
!Define_SMW_Sound1DFC_PodobooPan6 = $32
!Define_SMW_Sound1DFC_PodobooPan7 = $33
!Define_SMW_Sound1DFC_PodobooPan8 = $34

!Define_SMW_ChecksumCompliment = $5A5A
!Define_SMW_RegularLevelStatusBarScanlineEnd = $0024				;\ Info: Controls on which scanline a given IRQ should start. This one controls where the status bar scrolling ends in regular levels
!Define_SMW_Mode7RoomStatusBarScanlineEnd = $0024				;| Controls when mode 7 should start in most mode 7 boss rooms (Although Bowser's room disables the status bar, so this is not seen there)
!Define_SMW_MortonRoyRoomStatusBarScanlineEnd = $002D				;| Controls when mode 7 should start in Roy and Mortons's rooms (ie. The first scanline after the ceiling)
!Define_SMW_LudwigMortonRoyRoomMode7ScanlineEnd = $00AE				;/ Controls when mode 7 should stop in the Morton/Roy/Ludwig room so mode 1 layer 1 can render (ie. The first scanline of the bridge)

!Define_SMW_GlobalSpriteSizeAndVRAMLocation = !SpriteGFXLocationInVRAMLo_6000|!SpriteGFXLocationInVRAMHi_Add1000|!SpriteSize_8x8_16x16

!Define_SMW_Layer1TilemapVRAMLocation = $08					;\ Location of the layers 1/2/3/4 in VRAM. The location is $XX*$0400
!Define_SMW_Layer2TilemapVRAMLocation = $0C					;| The max value is $3F, but $1F covers the VRAM the SNES actually has.
!Define_SMW_Layer3TilemapVRAMLocation = $14					;|
!Define_SMW_Layer4TilemapVRAMLocation = $00					;/
!Define_SMW_Layer1TilemapVRAMLocation_Mode7 = $16				; Location of Layer 1's tilemap in VRAM in mode 7 bosses when mode 7 is disabled.
!Define_SMW_Layer1GFXVRAMLocation = $00						;\ Location of Layer 1/2/3/4's graphics in VRAM. The location is $XX*$1000
!Define_SMW_Layer2GFXVRAMLocation = $00						;| Note: Layer 1 and 2's graphics are hardcoded to be $0000, as SMW uses STZ to the VRAM address register. Also, Layer 2 is hardcoded to use layer 1's graphics outside of mode 7.
!Define_SMW_Layer3GFXVRAMLocation = $04						;|
!Define_SMW_Layer4GFXVRAMLocation = $00						;/
!Define_SMW_Layer1GFXVRAMLocation_Mode7 = $07					; Location of Layer 1's graphics in VRAM in mode 7 bosses when mode 7 is disabled.
!Define_SMW_Layer1TilemapSize = !LayerXTilemapSize_64x64			;\ Size of the layer 1/2/3/4 tilemaps
!Define_SMW_Layer2TilemapSize = !LayerXTilemapSize_64x64			;|
!Define_SMW_Layer3TilemapSize = !LayerXTilemapSize_64x64			;|
!Define_SMW_Layer4TilemapSize = !LayerXTilemapSize_32x32			;|
!Define_SMW_Layer1TilemapSize_Mode7 = !LayerXTilemapSize_64x32			;/
	!LayerXTilemapSize_32x32 = $00
	!LayerXTilemapSize_64x32 = $01
	!LayerXTilemapSize_32x64 = $02
	!LayerXTilemapSize_64x64 = $03

!Define_SMW_LevelID_ChangeOverworldPalette = ($0125-$DC)			;\ Note: Valid values are $0000-$0024/$0101-$013B. If using the latter range, add "-$DC" otherwise it won't work correctly.
!Define_SMW_LevelID_ChangeKoopaColors = ($0125-$DC)				;| LM: Lets you modify these in the "Change Special World Levels" dialog.
!Define_SMW_LevelID_ChangeSP2GFX = ($0125-$DC)					;/
!Define_SMW_LevelID_IggysCastle = ($0101-$DC)					;\ Note: Same ranges as above.
!Define_SMW_LevelID_MortonsCastle = ($0007)					;| LM: "Change Boss Sequence Levels"
!Define_SMW_LevelID_LemmysCastle = ($011C-$DC)					;|
!Define_SMW_LevelID_LudwigsCastle = ($000E)					;|
!Define_SMW_LevelID_RoysCastle = ($0020)					;|
!Define_SMW_LevelID_WendysCastle = ($001A)					;|
!Define_SMW_LevelID_LarrysCastle = ($0110-$DC)					;|
!Define_SMW_LevelID_FrontDoor = ($010D-$DC)					;|
!Define_SMW_LevelID_BackDoor = ($010E-$DC)					;|
!Define_SMW_LevelID_EarthquakeEvent = ($0018)					;|
!Define_SMW_LevelID_UseSecretExitForBoss = ($0013)				;/
!Define_SMW_LevelID_NorSpr032_LedgeDryBones_ThrowsBones = ($010D-$DC)		; Level that makes normal sprite 032 throw bones.
!Define_SMW_LevelID_ChocolateIsland2 = ($0024)					; Level that uses Chocolate Island 2's screen exit gimmick.
!Define_SMW_LevelID_IntroSublevel = ($C5+$24)					;\ Note: Must not be $00. If $25 or higher, add "+$24" otherwise it won't work correctly.
!Define_SMW_LevelID_TitleScreenSublevel = ($C7+$24)				;/

!Define_SMW_Submap_SlowerEmergingMontyMoles = !Define_SMW_Overworld_YoshisIsland	; Submap that makes monty moles emerge out of the ground slower.
!Define_SMW_Submap_MoreAgressiveHammerBro = !Define_SMW_Overworld_MainMap		; Submap that makes Hammer Bros throw hammers more often.

!Define_SMW_Timer_DisplayIntroMessage = $B0					; How long the intro message should display for before allowing the player to close it.
!Define_SMW_Timer_DisplayNintendoPresents = $40					; How long "Nintendo Presents" will display for.

!Define_SMW_Counter_StartingLives = 04						; How many lives the player starts with when loading a save file, minus 01.
!Define_SMW_Counter_TotalExits = 96						; How many exits are needed for the file select screen to display your exit count differently
!Define_SMW_Graphics_StartOfDynamicSpriteTiles = $0800				; Offset to the graphics for Yoshi, baby Yoshi, and the podoboo in the decompressed GFX33.

!Define_SMW_Physics_PMeterMax = $70						; How long the player must run for before being able to sprint.
!Define_SMW_Misc_SaveFileSize = $008F						; How many bytes make up a save file.

!Define_SMW_Overworld_MainMap = $00						;\ IDs for the submaps
!Define_SMW_Overworld_YoshisIsland = $01					;| Do not edit!
!Define_SMW_Overworld_VanillaDome = $02						;|
!Define_SMW_Overworld_ForestOfIlluision = $03					;|
!Define_SMW_Overworld_ValleyOfBowser = $04					;|
!Define_SMW_Overworld_SpecialWorld = $05					;|
!Define_SMW_Overworld_StarWorld = $06						;/


!Define_SMW_SizeOfGameModePtrs = $02
!Define_SMW_GameMode00_LoadNintendoPresents = (SMW_InitAndMainLoop_GameModePtrs_GameMode00_LoadNintendoPresents/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode01_ShowNintendoPresents = (SMW_InitAndMainLoop_GameModePtrs_GameMode01_ShowNintendoPresents/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode02_FadeOutToTitleScreen = (SMW_InitAndMainLoop_GameModePtrs_GameMode02_FadeOutToTitleScreen/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode03_LoadTitleScreenSublevel = (SMW_InitAndMainLoop_GameModePtrs_GameMode03_LoadTitleScreenSublevel/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode04_PrepareTitleScreen = (SMW_InitAndMainLoop_GameModePtrs_GameMode04_PrepareTitleScreen/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode05_FadeInToTitleScreen = (SMW_InitAndMainLoop_GameModePtrs_GameMode05_FadeInToTitleScreen/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode06_CircleEffect = (SMW_InitAndMainLoop_GameModePtrs_GameMode06_CircleEffect/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode07_TitleScreenDemo = (SMW_InitAndMainLoop_GameModePtrs_GameMode07_TitleScreenDemo/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode08_FileSelect = (SMW_InitAndMainLoop_GameModePtrs_GameMode08_FileSelect/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode09_EraseFile = (SMW_InitAndMainLoop_GameModePtrs_GameMode09_EraseFile/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode0A_PlayerSelect = (SMW_InitAndMainLoop_GameModePtrs_GameMode0A_PlayerSelect/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode0B_FadeOutToOverworld = (SMW_InitAndMainLoop_GameModePtrs_GameMode0B_FadeOutToOverworld/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode0C_LoadOverworld = (SMW_InitAndMainLoop_GameModePtrs_GameMode0C_LoadOverworld/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode0D_FadeInToOverworld = (SMW_InitAndMainLoop_GameModePtrs_GameMode0D_FadeInToOverworld/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode0E_ShowOverworld = (SMW_InitAndMainLoop_GameModePtrs_GameMode0E_ShowOverworld/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode0F_MosaicFadeOutToLevel = (SMW_InitAndMainLoop_GameModePtrs_GameMode0F_MosaicFadeOutToLevel/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode10_BufferLevelLoadMessage = (SMW_InitAndMainLoop_GameModePtrs_GameMode10_BufferLevelLoadMessage/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode11_LoadSublevel = (SMW_InitAndMainLoop_GameModePtrs_GameMode11_LoadSublevel/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode12_PrepareLevel = (SMW_InitAndMainLoop_GameModePtrs_GameMode12_PrepareLevel/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode13_MosaicFadeInToLevel = (SMW_InitAndMainLoop_GameModePtrs_GameMode13_MosaicFadeInToLevel/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode14_InLevel = (SMW_InitAndMainLoop_GameModePtrs_GameMode14_InLevel/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode15_FadeOutToDeathMessage = (SMW_InitAndMainLoop_GameModePtrs_GameMode15_FadeOutToDeathMessage/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode16_LoadDeathMessage = (SMW_InitAndMainLoop_GameModePtrs_GameMode16_LoadDeathMessage/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode17_ShowDeathMessage = (SMW_InitAndMainLoop_GameModePtrs_GameMode17_ShowDeathMessage/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode18_FadeOutToCutscene = (SMW_InitAndMainLoop_GameModePtrs_GameMode18_FadeOutToCutscene/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode19_Cutscene = (SMW_InitAndMainLoop_GameModePtrs_GameMode19_Cutscene/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode1A_FadeOutToCredits = (SMW_InitAndMainLoop_GameModePtrs_GameMode1A_FadeOutToCredits/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode1B_EndingCinema = (SMW_InitAndMainLoop_GameModePtrs_GameMode1B_EndingCinema/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode1C_FadeOutToYoshisHouse = (SMW_InitAndMainLoop_GameModePtrs_GameMode1C_FadeOutToYoshisHouse/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode1D_LoadYoshisHouse = (SMW_InitAndMainLoop_GameModePtrs_GameMode1D_LoadYoshisHouse/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode1E_FadeInToYoshisHouse = (SMW_InitAndMainLoop_GameModePtrs_GameMode1E_FadeInToYoshisHouse/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode1F_ShowYoshisHouse = (SMW_InitAndMainLoop_GameModePtrs_GameMode1F_ShowYoshisHouse/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode20_FadeOutToEnemyRollcallDelay = (SMW_InitAndMainLoop_GameModePtrs_GameMode20_FadeOutToEnemyRollcallDelay/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode21_DelayEnemyRollcall = (SMW_InitAndMainLoop_GameModePtrs_GameMode21_DelayEnemyRollcall/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode22_FadeOutToEnemyRollcall = (SMW_InitAndMainLoop_GameModePtrs_GameMode22_FadeOutToEnemyRollcall/!Define_SMW_SizeOfGameModePtrs)
!Define_SMW_GameMode23_LoadEnemyRollcallScreen = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$01
!Define_SMW_GameMode24_FadeInToEnemyRollcall = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$02
!Define_SMW_GameMode25_ShowEnemyRollcallScreen = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$03
!Define_SMW_GameMode26_FadeOutToTheEnd = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$04
!Define_SMW_GameMode27_LoadTheEnd = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$05
!Define_SMW_GameMode28_ShowTheEnd = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$06
!Define_SMW_GameMode29_DoNothingOnTheEndScreen = (!Define_SMW_GameMode22_FadeOutToEnemyRollcall)+$07

!Define_SMW_SizeOfPlayerStatePtrs = $02
!Define_SMW_PlayerState00_Normal = (SMW_GameMode14_InLevel_PlayerStatePtrs_PlayerState00_Normal/!Define_SMW_SizeOfPlayerStatePtrs)
!Define_SMW_PlayerState01_PowerDown = (!Define_SMW_PlayerState00_Normal)+$01
!Define_SMW_PlayerState02_Grow = (!Define_SMW_PlayerState00_Normal)+$02
!Define_SMW_PlayerState03_GotCape = (!Define_SMW_PlayerState00_Normal)+$03
!Define_SMW_PlayerState04_GotFlower = (!Define_SMW_PlayerState00_Normal)+$04
!Define_SMW_PlayerState05_EnterHorizontalPipe = (!Define_SMW_PlayerState00_Normal)+$05
!Define_SMW_PlayerState06_EnterVerticalPipe = (!Define_SMW_PlayerState00_Normal)+$06
!Define_SMW_PlayerState07_ShootOutOfPipe = (!Define_SMW_PlayerState00_Normal)+$07
!Define_SMW_PlayerState08_WarpToYoshiWingsBonus = (!Define_SMW_PlayerState00_Normal)+$08
!Define_SMW_PlayerState09_Death = (!Define_SMW_PlayerState00_Normal)+$09
!Define_SMW_PlayerState0A_NoYoshiCutscene = (!Define_SMW_PlayerState00_Normal)+$0A
!Define_SMW_PlayerState0B_RescuedPeach = (!Define_SMW_PlayerState00_Normal)+$0B
!Define_SMW_PlayerState0C_CastleDestructionMoves = (!Define_SMW_PlayerState00_Normal)+$0C
!Define_SMW_PlayerState0D_DoAbsolutelyNothing = (!Define_SMW_PlayerState00_Normal)+$0D

!Define_SMW_NorSpr_1656Prop_DisappearAsSmokeCloud = $80
!Define_SMW_NorSpr_1656Prop_HopInOrKickShells = $40
!Define_SMW_NorSpr_1656Prop_DiesWhenJumpedOn = $20
!Define_SMW_NorSpr_1656Prop_SafeToJumpOn = $10
!Define_SMW_NorSpr_1656Prop_ObjectClipping = $0F
	!Define_SMW_NorSpr_1656Prop_ObjectClipping00 = $00
	!Define_SMW_NorSpr_1656Prop_ObjectClipping01 = $01
	!Define_SMW_NorSpr_1656Prop_ObjectClipping02 = $02
	!Define_SMW_NorSpr_1656Prop_ObjectClipping03 = $03
	!Define_SMW_NorSpr_1656Prop_ObjectClipping04 = $04
	!Define_SMW_NorSpr_1656Prop_ObjectClipping05 = $05
	!Define_SMW_NorSpr_1656Prop_ObjectClipping06 = $06
	!Define_SMW_NorSpr_1656Prop_ObjectClipping07 = $07
	!Define_SMW_NorSpr_1656Prop_ObjectClipping08 = $08
	!Define_SMW_NorSpr_1656Prop_ObjectClipping09 = $09
	!Define_SMW_NorSpr_1656Prop_ObjectClipping0A = $0A
	!Define_SMW_NorSpr_1656Prop_ObjectClipping0B = $0B
	!Define_SMW_NorSpr_1656Prop_ObjectClipping0C = $0C
	!Define_SMW_NorSpr_1656Prop_ObjectClipping0D = $0D
	!Define_SMW_NorSpr_1656Prop_ObjectClipping0E = $0E
	!Define_SMW_NorSpr_1656Prop_ObjectClipping0F = $0F

!Define_SMW_NorSpr_1662Prop_FallWhenKilled = $80
!Define_SMW_NorSpr_1662Prop_UseShellAsDeathFrame = $40
!Define_SMW_NorSpr_1662Prop_SpriteClipping = $3F
	!Define_SMW_NorSpr_1662Prop_SpriteClipping00 = $00
	!Define_SMW_NorSpr_1662Prop_SpriteClipping01 = $01
	!Define_SMW_NorSpr_1662Prop_SpriteClipping02 = $02
	!Define_SMW_NorSpr_1662Prop_SpriteClipping03 = $03
	!Define_SMW_NorSpr_1662Prop_SpriteClipping04 = $04
	!Define_SMW_NorSpr_1662Prop_SpriteClipping05 = $05
	!Define_SMW_NorSpr_1662Prop_SpriteClipping06 = $06
	!Define_SMW_NorSpr_1662Prop_SpriteClipping07 = $07
	!Define_SMW_NorSpr_1662Prop_SpriteClipping08 = $08
	!Define_SMW_NorSpr_1662Prop_SpriteClipping09 = $09
	!Define_SMW_NorSpr_1662Prop_SpriteClipping0A = $0A
	!Define_SMW_NorSpr_1662Prop_SpriteClipping0B = $0B
	!Define_SMW_NorSpr_1662Prop_SpriteClipping0C = $0C
	!Define_SMW_NorSpr_1662Prop_SpriteClipping0D = $0D
	!Define_SMW_NorSpr_1662Prop_SpriteClipping0E = $0E
	!Define_SMW_NorSpr_1662Prop_SpriteClipping0F = $0F
	!Define_SMW_NorSpr_1662Prop_SpriteClipping10 = $10
	!Define_SMW_NorSpr_1662Prop_SpriteClipping11 = $11
	!Define_SMW_NorSpr_1662Prop_SpriteClipping12 = $12
	!Define_SMW_NorSpr_1662Prop_SpriteClipping13 = $13
	!Define_SMW_NorSpr_1662Prop_SpriteClipping14 = $14
	!Define_SMW_NorSpr_1662Prop_SpriteClipping15 = $15
	!Define_SMW_NorSpr_1662Prop_SpriteClipping16 = $16
	!Define_SMW_NorSpr_1662Prop_SpriteClipping17 = $17
	!Define_SMW_NorSpr_1662Prop_SpriteClipping18 = $18
	!Define_SMW_NorSpr_1662Prop_SpriteClipping19 = $19
	!Define_SMW_NorSpr_1662Prop_SpriteClipping1A = $1A
	!Define_SMW_NorSpr_1662Prop_SpriteClipping1B = $1B
	!Define_SMW_NorSpr_1662Prop_SpriteClipping1C = $1C
	!Define_SMW_NorSpr_1662Prop_SpriteClipping1D = $1D
	!Define_SMW_NorSpr_1662Prop_SpriteClipping1E = $1E
	!Define_SMW_NorSpr_1662Prop_SpriteClipping1F = $1F
	!Define_SMW_NorSpr_1662Prop_SpriteClipping20 = $20
	!Define_SMW_NorSpr_1662Prop_SpriteClipping21 = $21
	!Define_SMW_NorSpr_1662Prop_SpriteClipping22 = $22
	!Define_SMW_NorSpr_1662Prop_SpriteClipping23 = $23
	!Define_SMW_NorSpr_1662Prop_SpriteClipping24 = $24
	!Define_SMW_NorSpr_1662Prop_SpriteClipping25 = $25
	!Define_SMW_NorSpr_1662Prop_SpriteClipping26 = $26
	!Define_SMW_NorSpr_1662Prop_SpriteClipping27 = $27
	!Define_SMW_NorSpr_1662Prop_SpriteClipping28 = $28
	!Define_SMW_NorSpr_1662Prop_SpriteClipping29 = $29
	!Define_SMW_NorSpr_1662Prop_SpriteClipping2A = $2A
	!Define_SMW_NorSpr_1662Prop_SpriteClipping2B = $2B
	!Define_SMW_NorSpr_1662Prop_SpriteClipping2C = $2C
	!Define_SMW_NorSpr_1662Prop_SpriteClipping2D = $2D
	!Define_SMW_NorSpr_1662Prop_SpriteClipping2E = $2E
	!Define_SMW_NorSpr_1662Prop_SpriteClipping2F = $2F
	!Define_SMW_NorSpr_1662Prop_SpriteClipping30 = $30
	!Define_SMW_NorSpr_1662Prop_SpriteClipping31 = $31
	!Define_SMW_NorSpr_1662Prop_SpriteClipping32 = $32
	!Define_SMW_NorSpr_1662Prop_SpriteClipping33 = $33
	!Define_SMW_NorSpr_1662Prop_SpriteClipping34 = $34
	!Define_SMW_NorSpr_1662Prop_SpriteClipping35 = $35
	!Define_SMW_NorSpr_1662Prop_SpriteClipping36 = $36
	!Define_SMW_NorSpr_1662Prop_SpriteClipping37 = $37
	!Define_SMW_NorSpr_1662Prop_SpriteClipping38 = $38
	!Define_SMW_NorSpr_1662Prop_SpriteClipping39 = $39
	!Define_SMW_NorSpr_1662Prop_SpriteClipping3A = $3A
	!Define_SMW_NorSpr_1662Prop_SpriteClipping3B = $3B
	!Define_SMW_NorSpr_1662Prop_SpriteClipping3C = $3C
	!Define_SMW_NorSpr_1662Prop_SpriteClipping3D = $3D
	!Define_SMW_NorSpr_1662Prop_SpriteClipping3E = $3E
	!Define_SMW_NorSpr_1662Prop_SpriteClipping3F = $3F

!Define_SMW_NorSpr_166EProp_OnlyInteractWithLayer1 = $80
!Define_SMW_NorSpr_166EProp_DisableSplashing = $40
!Define_SMW_NorSpr_166EProp_ImmuneToCape = $20
!Define_SMW_NorSpr_166EProp_ImmuneToFire = $10
!Define_SMW_NorSpr_166EProp_Palette = $0E
	!Define_SMW_NorSpr_166EProp_Palette08 = $00
	!Define_SMW_NorSpr_166EProp_Palette09 = $02
	!Define_SMW_NorSpr_166EProp_Palette0A = $04
	!Define_SMW_NorSpr_166EProp_Palette0B = $06
	!Define_SMW_NorSpr_166EProp_Palette0C = $08
	!Define_SMW_NorSpr_166EProp_Palette0D = $0A
	!Define_SMW_NorSpr_166EProp_Palette0E = $0C
	!Define_SMW_NorSpr_166EProp_Palette0F = $0E
!Define_SMW_NorSpr_166EProp_UseSP3And4 = $01

!Define_SMW_NorSpr_167AProp_UseNonDefaultPlayerInteraction = $80
!Define_SMW_NorSpr_167AProp_GivePowerupWhenEaten = $40
!Define_SMW_NorSpr_167AProp_ProcessPlayerInteractionEveryFrame = $20
!Define_SMW_NorSpr_167AProp_CantBeKickedLikeShell = $10
!Define_SMW_NorSpr_167AProp_DontBecomeShellWhenStunned = $08
!Define_SMW_NorSpr_167AProp_TrackWhenOffScreen = $04
!Define_SMW_NorSpr_167AProp_InvincibleToMostThings = $02
!Define_SMW_NorSpr_167AProp_DontDisableClippingWhenStarKilled = $01

!Define_SMW_NorSpr_1686Prop_DisableObjectClipping = $80
!Define_SMW_NorSpr_1686Prop_SpawnsNewSprite = $40
!Define_SMW_NorSpr_1686Prop_DontBecomeCoinOnGoalTapeTrigger = $20
!Define_SMW_NorSpr_1686Prop_DontChangeDirectionWhenTouched = $10
!Define_SMW_NorSpr_1686Prop_DisableSpriteClipping = $08
!Define_SMW_NorSpr_1686Prop_DisableGroundShifting = $04
!Define_SMW_NorSpr_1686Prop_StayInYoshisMouth = $02
!Define_SMW_NorSpr_1686Prop_Inedible = $01

!Define_SMW_NorSpr_190FProp_DontGetStuckInWallsWhenCarried = $80
!Define_SMW_NorSpr_190FProp_ImmuneToSilverPSwitch = $40
!Define_SMW_NorSpr_190FProp_2TileTallDeathFrame = $20
!Define_SMW_NorSpr_190FProp_CanBeJumpedOnWithUpwardYSpeed = $10
!Define_SMW_NorSpr_190FProp_5FireballHP = $08
!Define_SMW_NorSpr_190FProp_ImmuneToSliding = $04
!Define_SMW_NorSpr_190FProp_DontDespawnOnLevelEnd = $02
!Define_SMW_NorSpr_190FProp_CanPassThroughPlaformFromBelow = $01

!Define_SMW_SizeOfNorSprStatusPtrs = $02
!Define_SMW_NorSprStatus00_EmptySlot = (SMW_ProcessNormalSprites_SpriteStatusPtr_NorSprStatus00_EmptySlot/!Define_SMW_SizeOfNorSprStatusPtrs)
!Define_SMW_NorSprStatus01_Init = (!Define_SMW_NorSprStatus00_EmptySlot)+$01
!Define_SMW_NorSprStatus02_Dead = (!Define_SMW_NorSprStatus00_EmptySlot)+$02
!Define_SMW_NorSprStatus03_Smushed = (!Define_SMW_NorSprStatus00_EmptySlot)+$03
!Define_SMW_NorSprStatus04_SpinJumpKill = (!Define_SMW_NorSprStatus00_EmptySlot)+$04
!Define_SMW_NorSprStatus05_SinkInLava = (!Define_SMW_NorSprStatus00_EmptySlot)+$05
!Define_SMW_NorSprStatus06_GoalCoins = (!Define_SMW_NorSprStatus00_EmptySlot)+$06
!Define_SMW_NorSprStatus07_InLimbo = (!Define_SMW_NorSprStatus00_EmptySlot)+$07
!Define_SMW_NorSprStatus08_Normal = (SMW_ProcessNormalSprites_SpriteStatusPtr_NorSprStatus08_Normal/!Define_SMW_SizeOfNorSprStatusPtrs)
!Define_SMW_NorSprStatus09_Stunned = (!Define_SMW_NorSprStatus08_Normal)+$01
!Define_SMW_NorSprStatus0A_Kicked = (!Define_SMW_NorSprStatus08_Normal)+$02
!Define_SMW_NorSprStatus0B_Carried = (!Define_SMW_NorSprStatus08_Normal)+$03
!Define_SMW_NorSprStatus0C_GoalPowerUp = (!Define_SMW_NorSprStatus08_Normal)+$04

!Define_SMW_StripeImage_TitleScreenLayer3 = SMW_LoadStripeImage_StripeImagePtrs_TitleScreen
!Define_SMW_StripeImage_OverworldBorder = SMW_LoadStripeImage_StripeImagePtrs_OverworldBorder
!Define_SMW_StripeImage_RemoveTextBox = SMW_LoadStripeImage_StripeImagePtrs_RemoveTextBox
!Define_SMW_StripeImage_ContinueEndText = SMW_LoadStripeImage_StripeImagePtrs_ContinueEndText
!Define_SMW_StripeImage_CookieMountainCutsceneBG = SMW_LoadStripeImage_StripeImagePtrs_CookieMountainCutsceneBG
!Define_SMW_StripeImage_XPlayerGameText = SMW_LoadStripeImage_StripeImagePtrs_XPlayerGameText
!Define_SMW_StripeImage_ShowScrollArrows = SMW_LoadStripeImage_StripeImagePtrs_ShowScrollArrows
!Define_SMW_StripeImage_RemoveScrollArrows = SMW_LoadStripeImage_StripeImagePtrs_RemoveScrollArrows
!Define_SMW_StripeImage_CloseOverworldPrompt = SMW_LoadStripeImage_StripeImagePtrs_CloseOverworldPrompt
!Define_SMW_StripeImage_SaveMenuText = SMW_LoadStripeImage_StripeImagePtrs_SaveMenuText
!Define_SMW_StripeImage_CastleDestructionText = SMW_LoadStripeImage_StripeImagePtrs_CastleDestructionText
!Define_SMW_StripeImage_CaveCutsceneBG = SMW_LoadStripeImage_StripeImagePtrs_CaveCutsceneBG
!Define_SMW_StripeImage_ChocolatIslandCutsceneBG = SMW_LoadStripeImage_StripeImagePtrs_ChocolatIslandCutsceneBG
!Define_SMW_StripeImage_CutsceneCastle = SMW_LoadStripeImage_StripeImagePtrs_CutsceneCastle
!Define_SMW_StripeImage_CutsceneBorder = SMW_LoadStripeImage_StripeImagePtrs_CutsceneBorder
!Define_SMW_StripeImage_TheEndText = SMW_LoadStripeImage_StripeImagePtrs_TheEndText
!Define_SMW_StripeImage_CreditsEnemyNames = SMW_LoadStripeImage_StripeImagePtrs_CreditsEnemyNames
!Define_SMW_StripeImage_OverworldCutsceneBG = SMW_LoadStripeImage_StripeImagePtrs_OverworldCutsceneBG

!Define_SMW_SizeOfNorSprPtrs = $02
!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr000_GreenNakedKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr001_RedNakedKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$01
!Define_SMW_SpriteID_NorSpr002_BlueNakedKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$02
!Define_SMW_SpriteID_NorSpr003_YellowNakedKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$03
!Define_SMW_SpriteID_NorSpr004_GreenKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$04
!Define_SMW_SpriteID_NorSpr005_RedKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$05
!Define_SMW_SpriteID_NorSpr006_BlueKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$06
!Define_SMW_SpriteID_NorSpr007_YellowKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$07
!Define_SMW_SpriteID_NorSpr008_LeftFlyingGreenParaKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$08
!Define_SMW_SpriteID_NorSpr009_BouncingGreenParaKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$09
!Define_SMW_SpriteID_NorSpr00A_VerticalRedParaKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$0A
!Define_SMW_SpriteID_NorSpr00B_HorizontalRedParaKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$0B
!Define_SMW_SpriteID_NorSpr00C_YellowParaKoopa = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$0C
!Define_SMW_SpriteID_NorSpr00D_BobOmb = (!Define_SMW_SpriteID_NorSpr000_GreenNakedKoopa)+$0D
!Define_SMW_SpriteID_NorSpr00E_Keyhole = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr00E_Keyhole/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr00F_Goomba = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr00F_Goomba/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr010_ParaGoomba = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr010_ParaGoomba/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr011_BuzzyBeetle = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr011_BuzzyBeetle/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr012_Unused = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr012_Unused/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr013_Spiny = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr013_Spiny/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr014_SpinyEgg = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr014_SpinyEgg/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr015_HorizontalCheepCheep = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr015_HorizontalCheepCheep/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr016_VerticalCheepCheep = (!Define_SMW_SpriteID_NorSpr015_HorizontalCheepCheep)+$01
!Define_SMW_SpriteID_NorSpr017_GeneratorCheepCheep = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr017_GeneratorCheepCheep/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr018_SurfaceJumpingCheepCheep = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr018_SurfaceJumpingCheepCheep/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr019_DisplayMessage = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr019_DisplayMessage/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr01A_ClassicPiranhaPlant = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr01A_ClassicPiranhaPlant/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr01B_Football = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr01B_Football/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr01C_BulletBill = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr01C_BulletBill/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr01D_HoppingFlame = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr01D_HoppingFlame/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr01E_Lakitu = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr01E_Lakitu/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr01F_MagiKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr01F_MagiKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr020_Magic = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr020_Magic/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr021_MovingCoin = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr021_MovingCoin/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr022_GreenVerticalNetKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr022_GreenVerticalNetKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr023_RedVerticalNetKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr023_RedVerticalNetKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr024_GreenHorizontalNetKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr024_GreenHorizontalNetKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr025_RedHorizontalNetKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr025_RedHorizontalNetKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr026_Thwomp = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr026_Thwomp/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr027_Thwimp = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr027_Thwimp/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr028_BigBoo = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr028_BigBoo/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr029_KoopaKids = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr029_KoopaKids/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr02A_UpsideDownPiranhaPlant = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr02A_UpsideDownPiranhaPlant/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr02B_SumoLightning = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr02B_SumoLightning/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr02C_YoshiEgg = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr02C_YoshiEgg/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr02D_BabyYoshi = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr02D_BabyYoshi/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr02E_SpikeTop = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr02E_SpikeTop/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr02F_PortableSpringboard = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr02F_PortableSpringboard/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr030_ThrowingDryBones = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr030_ThrowingDryBones/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr031_BonyBeetle = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr031_BonyBeetle/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr032_LedgeDryBones = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr032_LedgeDryBones/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr033_Podoboo = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr033_Podoboo/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr034_LudwigFireball = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr034_LudwigFireball/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr035_Yoshi = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr035_Yoshi/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr036_Unused = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr036_Unused/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr037_Boo = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr037_Boo/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr038_StraightEerie = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr038_StraightEerie/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr039_WavyEerie = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr039_WavyEerie/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr03A_FixedUrchin = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr03A_FixedUrchin/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr03B_WallDetectUrchin = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr03B_WallDetectUrchin/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr03C_WallFollowUrchin = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr03C_WallFollowUrchin/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr03D_RipVanFish = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr03D_RipVanFish/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr03E_PSwitch = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr03E_PSwitch/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr03F_ParachuteGoomba = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr03F_ParachuteGoomba/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr040_ParachuteBobOmb = (!Define_SMW_SpriteID_NorSpr03F_ParachuteGoomba)+$01
!Define_SMW_SpriteID_NorSpr041_LongJumpDolphin = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr041_LongJumpDolphin/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr042_ShortJumpDolphin = (!Define_SMW_SpriteID_NorSpr041_LongJumpDolphin)+$01
!Define_SMW_SpriteID_NorSpr043_VerticalDolphin = (!Define_SMW_SpriteID_NorSpr041_LongJumpDolphin)+$02
!Define_SMW_SpriteID_NorSpr044_TorpedoTed = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr044_TorpedoTed/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr045_DirectionalCoins = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr045_DirectionalCoins/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr046_DigginChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr046_DigginChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr047_SwimmingAndJumpingCheepCheep = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr047_SwimmingAndJumpingCheepCheep/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr048_DigginChuckRock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr048_DigginChuckRock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr049_ShiftingPipe = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr049_ShiftingPipe/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr04A_GoalSphere = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr04A_GoalSphere/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr04B_PipeLakitu = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr04B_PipeLakitu/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr04C_ExplodingBlock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr04C_ExplodingBlock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr04D_GroundMontyMole = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr04D_GroundMontyMole/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr04E_LedgeMontyMole = (!Define_SMW_SpriteID_NorSpr04D_GroundMontyMole)+$01
!Define_SMW_SpriteID_NorSpr04F_JumpingPiranhaPlant = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr04F_JumpingPiranhaPlant/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr050_FireSpittingJumpingPiranhaPlant = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr050_FireSpittingJumpingPiranhaPlant/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr051_Ninji = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr051_Ninji/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr052_MovingLedgeHole = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr052_MovingLedgeHole/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr053_ThrowBlock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr053_ThrowBlock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr054_ClimbingNetDoor = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr054_ClimbingNetDoor/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr055_HorizontalCheckerboardPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr056_HorizontalRockPlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$01
!Define_SMW_SpriteID_NorSpr057_VerticalCheckerboardPlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$02
!Define_SMW_SpriteID_NorSpr058_VerticalRockPlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$03
!Define_SMW_SpriteID_NorSpr059_HorizontalAndVerticalTurnBlockBridge = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr059_HorizontalAndVerticalTurnBlockBridge/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr05A_HorizontalTurnBlockBridge = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr05A_HorizontalTurnBlockBridge/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr05B_BrownBuoyantPlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$06
!Define_SMW_SpriteID_NorSpr05C_BuoyantCheckboardPlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$07
!Define_SMW_SpriteID_NorSpr05D_OrangeBuoyantPlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$08
!Define_SMW_SpriteID_NorSpr05E_FloatingOrangePlatform = (!Define_SMW_SpriteID_NorSpr055_HorizontalCheckerboardPlatform)+$09
!Define_SMW_SpriteID_NorSpr05F_BrownChainedPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr05F_BrownChainedPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr060_FlatPalaceSwitch = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr060_FlatPalaceSwitch/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr061_SkullRaft = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr061_SkullRaft/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr062_BrownLineGuidePlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr062_BrownLineGuidePlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr063_CheckerboardLineGuidePlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr063_CheckerboardLineGuidePlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr064_LineGuideRope = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr064_LineGuideRope/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr065_Chainsaw = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr065_Chainsaw/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr066_UpsideDownChainsaw = (!Define_SMW_SpriteID_NorSpr065_Chainsaw)+$01
!Define_SMW_SpriteID_NorSpr067_LineGuideGrinder = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr067_LineGuideGrinder/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr068_LineGuideFuzzy = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr068_LineGuideFuzzy/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr069_Unused = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr069_Unused/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr06A_CoinGameCloud = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr06A_CoinGameCloud/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr06B_LeftWallSpringboard = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr06B_LeftWallSpringboard/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr06C_RightWallSpringboard = (!Define_SMW_SpriteID_NorSpr06B_LeftWallSpringboard)+$01
!Define_SMW_SpriteID_NorSpr06D_InvisibleBlock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr06D_InvisibleBlock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr06E_DinoRhino = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr06E_DinoRhino/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr06F_DinoTorch = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr06F_DinoTorch/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr070_Pokey = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr070_Pokey/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr071_RedCapeSuperKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr071_RedCapeSuperKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr072_YellowCapeSuperKoopa = (!Define_SMW_SpriteID_NorSpr071_RedCapeSuperKoopa)+$01
!Define_SMW_SpriteID_NorSpr073_GroundSuperKoopa = (!Define_SMW_SpriteID_NorSpr071_RedCapeSuperKoopa)+$02
!Define_SMW_SpriteID_NorSpr074_Mushroom = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr074_Mushroom/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr075_FireFlower = (!Define_SMW_SpriteID_NorSpr074_Mushroom)+$01
!Define_SMW_SpriteID_NorSpr076_Star = (!Define_SMW_SpriteID_NorSpr074_Mushroom)+$02
!Define_SMW_SpriteID_NorSpr077_Feather = (!Define_SMW_SpriteID_NorSpr074_Mushroom)+$03
!Define_SMW_SpriteID_NorSpr078_1upMushroom = (!Define_SMW_SpriteID_NorSpr074_Mushroom)+$04
!Define_SMW_SpriteID_NorSpr079_VineHead = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr079_VineHead/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr07A_Fireworks = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$01
!Define_SMW_SpriteID_NorSpr07B_GoalTape = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$02
!Define_SMW_SpriteID_NorSpr07C_PrincessPeach = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$03
!Define_SMW_SpriteID_NorSpr07D_PBalloon = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$04
!Define_SMW_SpriteID_NorSpr07E_FlyingRedCoin = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$05
!Define_SMW_SpriteID_NorSpr07F_Flying1up = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$06
!Define_SMW_SpriteID_NorSpr080_Key = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$07
!Define_SMW_SpriteID_NorSpr081_ChangingItem = (!Define_SMW_SpriteID_NorSpr079_VineHead)+$08
!Define_SMW_SpriteID_NorSpr082_BonusGame = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr082_BonusGame/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr083_LeftFlyingBlock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr083_LeftFlyingBlock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr084_HorizontalFlyingBlock = (!Define_SMW_SpriteID_NorSpr083_LeftFlyingBlock)+$01
!Define_SMW_SpriteID_NorSpr085_Unused = (!Define_SMW_SpriteID_NorSpr083_LeftFlyingBlock)+$02
!Define_SMW_SpriteID_NorSpr086_Wiggler = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr086_Wiggler/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr087_LakituCloud = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr087_LakituCloud/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr088_WingedCage = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr088_WingedCage/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr089_Layer3Smasher = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr089_Layer3Smasher/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr08A_Bird = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr08A_Bird/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr08B_FireplaceSmoke = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr08B_FireplaceSmoke/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr08C_SideExitAndFireplace = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr08C_SideExitAndFireplace/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr08D_GhostHouseDoor = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr08D_GhostHouseDoor/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr08E_WarpHole = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr08E_WarpHole/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr08F_ScalePlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr08F_ScalePlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr090_GreenGasBubble = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr090_GreenGasBubble/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr091_CharginChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr091_CharginChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr092_SplittinChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr092_SplittinChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr093_BouncinChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr093_BouncinChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr094_WhistlinChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr094_WhistlinChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr095_ClappinChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr095_ClappinChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr096_CharginChuckCopy = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr096_CharginChuckCopy/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr097_PuntinChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr097_PuntinChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr098_PitchinChuck = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr098_PitchinChuck/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr099_VolcanoLotus = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr099_VolcanoLotus/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr09A_SumoBro = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr09A_SumoBro/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr09B_HammerBro = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr09B_HammerBro/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr09C_HammerBroPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr09C_HammerBroPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr09D_BubbleWithSprite = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr09D_BubbleWithSprite/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr09E_BallNChain = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr09E_BallNChain/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr09F_BanzaiBill = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr09F_BanzaiBill/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A0_ActivateBowserBattle = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A0_ActivateBowserBattle/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A1_BowserBowlingBall = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A1_BowserBowlingBall/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A2_MechaKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A2_MechaKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A3_GreyChainedPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A3_GreyChainedPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A4_SpikeBall = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A4_SpikeBall/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A5_Sparky = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A5_Sparky/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A6_Hothead = (!Define_SMW_SpriteID_NorSpr0A5_Sparky)+$01
!Define_SMW_SpriteID_NorSpr0A7_IggyBall = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A7_IggyBall/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A8_Blargg = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A8_Blargg/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0A9_Reznor = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0A9_Reznor/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0AA_Fishbone = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0AA_Fishbone/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0AB_Rex = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0AB_Rex/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0AC_DownFirstWoodenSpike = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0AC_DownFirstWoodenSpike/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0AD_UpDownFirstWoodenSpike = (!Define_SMW_SpriteID_NorSpr0AC_DownFirstWoodenSpike)+$01
!Define_SMW_SpriteID_NorSpr0AE_FishinBoo = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0AE_FishinBoo/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0AF_BooBlock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0AF_BooBlock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B0_ReflectingBooBuddies = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B0_ReflectingBooBuddies/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B1_CreateEatBlock = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B1_CreateEatBlock/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B2_FallingSpike = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B2_FallingSpike/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B3_BowserStatueFire = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B3_BowserStatueFire/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B4_NonLineGuideGrinder = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B4_NonLineGuideGrinder/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B5_SinkingFireball = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B5_SinkingFireball/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B6_ReflectingPodoboo = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B6_ReflectingPodoboo/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B7_CarrotTopLiftUpperRight = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B7_CarrotTopLiftUpperRight/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0B8_CarrotTopLiftUpperLeft = (!Define_SMW_SpriteID_NorSpr0B7_CarrotTopLiftUpperRight)+$01
!Define_SMW_SpriteID_NorSpr0B9_MessageBox = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0B9_MessageBox/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0BA_TimedPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0BA_TimedPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0BB_MovingCastleStone = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0BB_MovingCastleStone/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0BC_BowserStatue = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0BC_BowserStatue/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0BD_SlidingNakedBlueKoopa = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0BD_SlidingNakedBlueKoopa/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0BE_Swooper = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0BE_Swooper/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0BF_MegaMole = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0BF_MegaMole/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C0_SinkingLavaPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C0_SinkingLavaPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C1_WingedPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C1_WingedPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C2_Blurp = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C2_Blurp/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C3_PorcuPuffer = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C3_PorcuPuffer/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C4_GreyFallingPlatform = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C4_GreyFallingPlatform/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C5_BigBooBoss = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C5_BigBooBoss/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C6_Spotlight = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C6_Spotlight/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C7_InvisibleMushroom = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C7_InvisibleMushroom/!Define_SMW_SizeOfNorSprPtrs)
!Define_SMW_SpriteID_NorSpr0C8_LightSwitch = (SMW_NorSprStatus08_Normal_NormalSpriteNormalPtrs_NorSpr0C8_LightSwitch/!Define_SMW_SizeOfNorSprPtrs)

!Define_SMW_SizeOfExtSprPtrs = $02
!Define_SMW_SpriteID_ExtSpr01_SmokePuff = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr01_SmokePuff/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr02_ReznorFireball = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr02_ReznorFireball/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr03_FlameRemnant = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr03_FlameRemnant/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr04_Hammer = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr04_Hammer/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr05_MarioFireball = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr05_MarioFireball/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr06_ThrownBone = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr06_ThrownBone/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr07_LavaSplash = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr07_LavaSplash/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr08_LauncherArm = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr08_LauncherArm/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr09_Unused = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr09_Unused/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr0A_CloudCoin = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr0A_CloudCoin/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr0B_PiranhaFireball = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr0B_PiranhaFireball/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr0C_VolcanoLotusFire = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr0C_VolcanoLotusFire/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr0D_Baseball = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr0D_Baseball/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr0E_WigglerFlower = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr0E_WigglerFlower/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr0F_SmokeTrail = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr0F_SmokeTrail/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr10_SpinJumpStars = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr10_SpinJumpStars/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr11_YoshiFireball = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr11_YoshiFireball/!Define_SMW_SizeOfExtSprPtrs)
!Define_SMW_SpriteID_ExtSpr12_BreathBubble = (SMW_ProcessExtendedSprites_ExtendedSpritePtrs_ExtSpr12_BreathBubble/!Define_SMW_SizeOfExtSprPtrs)

!Define_SMW_SizeOfBounceSprPtrs = $02
!Define_SMW_SpriteID_BounceSpr01_TurnBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr01_TurnBlock/!Define_SMW_SizeOfBounceSprPtrs)
!Define_SMW_SpriteID_BounceSpr02_NoteBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr02_NoteBlock/!Define_SMW_SizeOfBounceSprPtrs)
!Define_SMW_SpriteID_BounceSpr03_QuestionBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr03_QuestionBlock/!Define_SMW_SizeOfBounceSprPtrs)
!Define_SMW_SpriteID_BounceSpr04_SidewaysMovingBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr04_SidewaysMovingBlock/!Define_SMW_SizeOfBounceSprPtrs)
!Define_SMW_SpriteID_BounceSpr05_GlassBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr05_GlassBlock/!Define_SMW_SizeOfBounceSprPtrs)
!Define_SMW_SpriteID_BounceSpr06_OnOffBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr06_OnOffBlock/!Define_SMW_SizeOfBounceSprPtrs)
!Define_SMW_SpriteID_BounceSpr07_SpinningTurnBlock = (SMW_ProcessBounceAndSmokeSprites_BounceSpritePtrs_BounceSpr07_SpinningTurnBlock/!Define_SMW_SizeOfBounceSprPtrs)

!Define_SMW_SizeOfSmokeSprPtrs = $02
!Define_SMW_SpriteID_SmokeSpr01_PuffOfSmoke = (SMW_ProcessBounceAndSmokeSprites_SmokeSpritePtrs_SmokeSpr01_PuffOfSmoke/!Define_SMW_SizeOfSmokeSprPtrs)
!Define_SMW_SpriteID_SmokeSpr02_ContactEffect = (SMW_ProcessBounceAndSmokeSprites_SmokeSpritePtrs_SmokeSpr02_ContactEffect/!Define_SMW_SizeOfSmokeSprPtrs)
!Define_SMW_SpriteID_SmokeSpr03_TurnAroundSmoke = (SMW_ProcessBounceAndSmokeSprites_SmokeSpritePtrs_SmokeSpr03_TurnAroundSmoke/!Define_SMW_SizeOfSmokeSprPtrs)
!Define_SMW_SpriteID_SmokeSpr04_Unused = (SMW_ProcessBounceAndSmokeSprites_SmokeSpritePtrs_SmokeSpr04_Unused/!Define_SMW_SizeOfSmokeSprPtrs)
!Define_SMW_SpriteID_SmokeSpr05_Glitter = (SMW_ProcessBounceAndSmokeSprites_SmokeSpritePtrs_SmokeSpr05_Glitter/!Define_SMW_SizeOfSmokeSprPtrs)

!Define_SMW_SizeOfMExtSprPtrs = $02
!Define_SMW_SpriteID_MExtSpr01_BrickPiece = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr01_BrickPiece/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr02_SmallStar = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr02_SmallStar/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr03_EggShell = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr03_EggShell/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr04_PodobooFire = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr04_PodobooFire/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr05_SmallStar = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr05_SmallStar/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr06_RipVanFishZ = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr06_RipVanFishZ/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr07_WaterSplash = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr07_WaterSplash/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr08_UnusedMusicNote = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr08_UnusedMusicNote/!Define_SMW_SizeOfMExtSprPtrs)
	!Define_SMW_SpriteID_MExtSpr09_UnusedMusicNote = (!Define_SMW_SpriteID_MExtSpr08_UnusedMusicNote)+$01
!Define_SMW_SpriteID_MExtSpr0A_BooStream = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr0A_BooStream/!Define_SMW_SizeOfMExtSprPtrs)
!Define_SMW_SpriteID_MExtSpr0B_UnusedYoshiSmoke = (SMW_ProcessMinorExtendedSprites_MinorExtendedSpritesPtrs_MExtSpr0B_UnusedYoshiSmoke/!Define_SMW_SizeOfMExtSprPtrs)

!Define_SMW_SizeOfClusterSprPtrs = $02
!Define_SMW_SpriteID_ClusterSpr01_1up = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr01_1up/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr02_Unused = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr02_Unused/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr03_BooCeiling = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr03_BooCeiling/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr04_BooRing = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr04_BooRing/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr05_CandleFlame = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr05_CandleFlame/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr06_SumoBroFlame = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr06_SumoBroFlame/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr07_ReappearingBoo = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr07_ReappearingBoo/!Define_SMW_SizeOfClusterSprPtrs)
!Define_SMW_SpriteID_ClusterSpr08_DeathBatCeiling = (SMW_ProcessClusterSprites_ClusterSpritePtrs_ClusterSpr08_DeathBatCeiling/!Define_SMW_SizeOfClusterSprPtrs)

!Define_SMW_SizeOfGenSprPtrs = $02
!Define_SMW_SpriteID_GenSpr01_GenerateEerie = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr01_GenerateEerie/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr02_GenParachuteEnemy = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr02_GenParachuteEnemy/!Define_SMW_SizeOfGenSprPtrs)
	!Define_SMW_SpriteID_GenSpr03_GenParachuteGoomba = (!Define_SMW_SpriteID_GenSpr02_GenParachuteEnemy)+$01
	!Define_SMW_SpriteID_GenSpr04_GenParachuteBobOmb = (!Define_SMW_SpriteID_GenSpr02_GenParachuteEnemy)+$02
!Define_SMW_SpriteID_GenSpr05_GenerateLeftDolphins = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr05_GenerateLeftDolphins/!Define_SMW_SizeOfGenSprPtrs)
	!Define_SMW_SpriteID_GenSpr06_GenerateRightDolphins = (!Define_SMW_SpriteID_GenSpr05_GenerateLeftDolphins)+$01
!Define_SMW_SpriteID_GenSpr07_GenerateFish = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr07_GenerateFish/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr08_TurnOffRespawningSprite = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr08_TurnOffRespawningSprite/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr09_GenerateSuperKoopa = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr09_GenerateSuperKoopa/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr0A_GenerateBubbles = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr0A_GenerateBubbles/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr0B_GenerateBullet = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr0B_GenerateBullet/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr0C_GenerateSurroundingBullets = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr0C_GenerateSurroundingBullets/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr0D_GenerateDiagnalBullets = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr0D_GenerateDiagnalBullets/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr0E_GenerateFire = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr0E_GenerateFire/!Define_SMW_SizeOfGenSprPtrs)
!Define_SMW_SpriteID_GenSpr0F_TurnOffGenerator = (SMW_ProcessGeneratorSprite_GeneratorSprPtrs_GenSpr0F_TurnOffGenerator/!Define_SMW_SizeOfGenSprPtrs)

!Define_SMW_SizeOfShooterSprPtrs = $02
!Define_SMW_SpriteID_ShooterSpr01_BulletBillShooter = (SMW_ProcessShooterSprites_ShooterSprPtrs_ShooterSpr01_BulletBillShooter/!Define_SMW_SizeOfShooterSprPtrs)
!Define_SMW_SpriteID_ShooterSpr02_TorpedoShooter = (SMW_ProcessShooterSprites_ShooterSprPtrs_ShooterSpr02_TorpedoShooter/!Define_SMW_SizeOfShooterSprPtrs)
!Define_SMW_SpriteID_ShooterSpr03_Unused = (SMW_ProcessShooterSprites_ShooterSprPtrs_ShooterSpr03_Unused/!Define_SMW_SizeOfShooterSprPtrs)

!Define_SMW_SizeOfOWSprPtrs = $02
!Define_SMW_SpriteID_OWSpr01_Lakitu = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr01_Lakitu/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr02_BlueBird = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr02_BlueBird/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr03_CheepCheep = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr03_CheepCheep/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr04_PiranhaPlant = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr04_PiranhaPlant/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr05_Cloud = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr05_Cloud/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr06_KoopaKid = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr06_KoopaKid/!Define_SMW_SizeOfOWSprPtrs)
	!Define_SMW_OWSpr06_KoopaKid_LowestTriggerTile = $49
!Define_SMW_SpriteID_OWSpr07_Smoke = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr07_Smoke/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr08_BowserSign = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr08_BowserSign/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr09_Bowser = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr09_Bowser/!Define_SMW_SizeOfOWSprPtrs)
!Define_SMW_SpriteID_OWSpr0A_Boo = (SMW_ProcessOverworldSprites_OverworldSpritePtrs_OWSpr0A_Boo/!Define_SMW_SizeOfOWSprPtrs)

if !Define_Global_ROMToAssemble&(!ROM_SMW_E2|!ROM_SMASW_E) != $00
	!Define_SMW_Timer_DisplayIntroMessage = $90
	!Define_SMW_Physics_PMeterMax = $68
elseif !Define_Global_ROMToAssemble&(!ROM_SMW_E1) != $00
	!Define_SMW_Timer_DisplayIntroMessage = $90
	!Define_SMW_Physics_PMeterMax = $40
endif

if !Define_Global_ROMToAssemble&(!ROM_SMW_E1|!ROM_SMW_E2|!ROM_SMASW_E) != $00
	!Define_SMW_Counter_TimerFrames = $22
else
	!Define_SMW_Counter_TimerFrames = $28
endif