dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 000
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 001
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 002
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 003
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 004
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 005
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 006
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 007
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 008
dl SMW_LEVEL_L2_009					; 009
dw SMW_Backgrounds_Layer2_Water				:	db $FF	; 00A
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 00B
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 00C
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 00D
dl SMW_LEVEL_L2_00E					; 00E
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 00F
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 010
dw SMW_Backgrounds_Layer2_Water				:	db $FF	; 011
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 012
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 013
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 014
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 015
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 016
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 017
dw SMW_Backgrounds_Layer2_Water				:	db $FF	; 018
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 019
dl SMW_LEVEL_L2_01A					; 01A
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 01B
dw SMW_Backgrounds_Layer2_Rocks				:	db $FF	; 01C
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 01D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 01E
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 01F
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 020
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 021
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 022
dw SMW_Backgrounds_Layer2_Rocks				:	db $FF	; 023
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 024
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 025
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 026
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 027
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 028
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 029
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 02A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 02B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 02C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 02D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 02E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 02F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 030
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 031
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 032
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 033
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 034
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 035
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 036
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 037
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 038
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 039
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 03A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 03B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 03C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 03D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 03E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 03F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 040
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 041
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 042
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 043
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 044
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 045
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 046
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 047
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 048
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 049
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 04A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 04B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 04C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 04D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 04E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 04F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 050
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 051
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 052
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 053
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 054
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 055
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 056
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 057
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 058
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 059
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 05A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 05B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 05C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 05D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 05E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 05F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 060
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 061
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 062
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 063
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 064
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 065
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 066
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 067
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 068
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 069
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 06A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 06B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 06C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 06D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 06E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 06F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 070
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 071
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 072
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 073
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 074
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 075
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 076
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 077
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 078
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 079
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 07A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 07B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 07C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 07D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 07E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 07F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 080
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 081
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 082
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 083
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 084
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 085
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 086
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 087
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 088
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 089
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 08A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 08B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 08C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 08D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 08E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 08F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 090
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 091
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 092
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 093
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 094
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 095
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 096
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 097
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 098
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 099
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 09A
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 09B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 09C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 09D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 09E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 09F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A0
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A1
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A2
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A3
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A4
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A5
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A6
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A7
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A8
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0A9
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0AA
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0AB
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0AC
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0AD
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0AE
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0AF
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B0
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B1
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B2
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B3
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B4
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B5
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B6
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B7
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B8
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0B9
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0BA
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0BB
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0BC
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0BD
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0BE
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 0BF
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0C0
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0C1
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 0C2
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0C3
dl SMW_LEVEL_L2_0C4					; 0C4
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0C5
dw SMW_Backgrounds_Layer2_LargeHills			:	db $FF	; 0C6
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0C7
dw SMW_Backgrounds_Layer2_Stars				:	db $FF	; 0C8
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0C9
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0CA
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 0CB
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0CC
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0CD
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0CE
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 0CF
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0D0
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0D1
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 0D2
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0D3
dl SMW_LEVEL_L2_0D4					; 0D4
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0D5
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0D6
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 0D7
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 0D8
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0D9
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0DA
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0DB
dl SMW_LEVEL_L2_0DC					; 0DC
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 0DD
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0DE
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 0DF
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0E0
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0E1
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0E2
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0E3
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0E4
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0E5
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0E6
dl SMW_LEVEL_L2_0E7					; 0E7
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0E8
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 0E9
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 0EA
dl SMW_LEVEL_L2_0C4					; 0EB
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0EC
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0ED
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0EE
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 0EF
dl SMW_LEVEL_L2_0C4					; 0F0
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0F1
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0F2
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 0F3
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0F4
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0F5
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0F6
dw SMW_Backgrounds_Layer2_Black				:	db $FF	; 0F7
dw SMW_Backgrounds_Layer2_SunkenGhostShip		:	db $FF	; 0F8
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0F9
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0FA
dl SMW_LEVEL_L2_0C4					; 0FB
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0FC
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 0FD
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 0FE
dw SMW_Backgrounds_Layer2_SmallHills			:	db $FF	; 0FF
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 100
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 101
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 102
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 103
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 104
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 105
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 106
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 107
dw SMW_Backgrounds_Layer2_Rocks				:	db $FF	; 108
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 109
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 10A
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 10B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 10C
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 10D
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 10E
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 10F
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 110
dl SMW_LEVEL_L2_111					; 111
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 112
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 113
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 114
dl SMW_LEVEL_L2_115					; 115
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 116
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 117
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 118
dw SMW_Backgrounds_Layer2_Stars				:	db $FF	; 119
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 11A
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 11B
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 11C
dl SMW_LEVEL_L2_11D					; 11D
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 11E
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 11F
dw SMW_Backgrounds_Layer2_Water				:	db $FF	; 120
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 121
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 122
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 123
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 124
dw SMW_Backgrounds_Layer2_CloudyHills			:	db $FF	; 125
dw SMW_Backgrounds_Layer2_Forest			:	db $FF	; 126
dw SMW_Backgrounds_Layer2_Rocks				:	db $FF	; 127
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 128
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 129
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 12A
dw SMW_Backgrounds_Layer2_LargeHills			:	db $FF	; 12B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 12C
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 12D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 12E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 12F
dw SMW_Backgrounds_Layer2_Water				:	db $FF	; 130
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 131
dw SMW_Backgrounds_Layer2_Stars				:	db $FF	; 132
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 133
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 134
dw SMW_Backgrounds_Layer2_Stars				:	db $FF	; 135
dw SMW_Backgrounds_Layer2_Stars				:	db $FF	; 136
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 137
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 138
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 139
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 13A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 13B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 13C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 13D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 13E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 13F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 140
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 141
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 142
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 143
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 144
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 145
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 146
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 147
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 148
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 149
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 14A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 14B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 14C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 14D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 14E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 14F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 150
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 151
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 152
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 153
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 154
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 155
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 156
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 157
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 158
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 159
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 15A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 15B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 15C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 15D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 15E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 15F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 160
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 161
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 162
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 163
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 164
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 165
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 166
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 167
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 168
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 169
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 16A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 16B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 16C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 16D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 16E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 16F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 170
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 171
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 172
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 173
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 174
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 175
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 176
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 177
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 178
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 179
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 17A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 17B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 17C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 17D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 17E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 17F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 180
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 181
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 182
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 183
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 184
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 185
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 186
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 187
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 188
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 189
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 18A
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 18B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 18C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 18D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 18E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 18F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 190
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 191
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 192
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 193
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 194
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 195
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 196
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 197
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 198
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 199
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 19A
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 19B
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 19C
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 19D
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 19E
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 19F
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A0
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A1
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A2
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A3
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A4
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A5
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A6
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A7
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A8
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1A9
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1AA
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1AB
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1AC
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1AD
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1AE
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1AF
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B0
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B1
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B2
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B3
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B4
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B5
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B6
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B7
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B8
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1B9
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1BA
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 1BB
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 1BC
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1BD
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 1BE
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1BF
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 1C0
dw SMW_Backgrounds_Layer2_Water				:	db $FF	; 1C1
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1C2
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1C3
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1C4
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1C5
dw SMW_Backgrounds_Layer2_Mountains			:	db $FF	; 1C6
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1C7
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1C8
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1C9
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1CA
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1CB
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1CC
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 1CD
dl SMW_LEVEL_L2_1CE					; 1CE
dl SMW_LEVEL_L2_1CF					; 1CF
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 1D0
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1D1
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1D2
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1D3
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 1D4
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1D5
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1D6
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 1D7
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 1D8
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1D9
dl SMW_LEVEL_L2_0C4					; 1DA
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1DB
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1DC
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1DD
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1DE
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1DF
dw SMW_Backgrounds_Layer2_Clouds			:	db $FF	; 1E0
dw SMW_Backgrounds_Layer2_Rocks				:	db $FF	; 1E1
dl SMW_LEVEL_L2_1E2					; 1E2
dl SMW_LEVEL_L2_1E3					; 1E3
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 1E4
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1E5
dl SMW_LEVEL_L2_0C4					; 1E6
dl SMW_LEVEL_L2_0C4					; 1E7
dl SMW_LEVEL_L2_11D					; 1E8
dl SMW_LEVEL_L2_11D					; 1E9
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1EA
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1EB
dl SMW_LEVEL_L2_1EC					; 1EC
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1ED
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1EE
dl SMW_LEVEL_L2_1EF					; 1EF
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1F0
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1F1
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1F2
dl SMW_LEVEL_L2_1F3					; 1F3
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1F4
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1F5
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1F6
dw SMW_Backgrounds_Layer2_Bonus				:	db $FF	; 1F7
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1F8
dl SMW_LEVEL_L2_0C4					; 1F9
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1FA
dw SMW_Backgrounds_Layer2_GhostHouse			:	db $FF	; 1FB
dw SMW_Backgrounds_Layer2_Castle2			:	db $FF	; 1FC
dw SMW_Backgrounds_Layer2_Cave				:	db $FF	; 1FD
dw SMW_Backgrounds_Layer2_Castle			:	db $FF	; 1FE
dw SMW_Backgrounds_Layer2_Rocks2			:	db $FF	; 1FF
